Added Google analytics data attribute
hmrc/play-language pull request #5
Opened 2017-03-03 11:46 UTC by nehakannaujia

@shaileshp0110  : Please review and merge.

2017-03-03 12:04 UTC, nehakannaujia commented
@shaileshp0110  : Fixed Unit tests. Please review and merge.

2017-03-06 09:55 UTC, shaileshp0110 requested changes
Need to be optional field rather mandatory String

2017-03-06 10:36 UTC, merged

2017-03-06 14:04 UTC, ryanb93 commented on app/views/language_selection.scala.html
> +                    dataAttributes = Some(Map("journey-click" -> s"${appName.fold("")(a=>a)}:language: ${value.code}"))
Use appName.getOrElse("") instead of fold.

2017-03-06 14:09 UTC, ryanb93 commented on test/views/LanguageSelectionSpec.scala
> +      val html = views.html.language_selection.render(languageMap, langToUrl(_), None, Some("appName:language: cy-GB"), Welsh)
Shouldn't the Some here just contain the app name by itself, then the test should check that Welsh was correctly injected into the resulting string. At the moment I think that the test passes but is a little misleading, the full string would be:

"data-journey-click=\"appName:language: cy-GB\"":language: cy-GB\""

Based on the logic of:

s"${appName.fold("")(a=>a)}:language: ${value.code}"

2017-03-06 14:17 UTC, nehakannaujia commented on test/views/LanguageSelectionSpec.scala
> +      val html = views.html.language_selection.render(languageMap, langToUrl(_), None, Some("appName:language: cy-GB"), Welsh)
@ryanb93  Yeah that's correct. It should be only "appName" instead of complete string.